### ISSUE TITLE
Server is Closed-Source

### ISSUE THREAD

**Issue by xloem** [wireapp/wire-audio-video-signaling#11]
This issue is mentioned at https://crysp.uwaterloo.ca/opinion/wire/ , a review of Wire by a security researcher.

> The Wire client is open source—and open to analysis by security researchers—but the server software is not.

Notably, close-sourcing the server means that if anything happens to Wire Swiss, the ecosystem of Wire users dies with it.  Nobody can spin up their own server and keep things running into the future.  And of course, the server may have security vulnerabilities that nobody can safely check for, because the code is unavailable.

**Comment by IsidorDG** [comment]
I saw the comment "The server code will be released in Q1 2017.".
Can you give us some more details when are you planning to do so and what are the conditions/license. The full server software? Will this mean someone could run his own private "Wire" environment? Would it also be possible to connect Wire based communication with an Wire-derivative messenger?
Do you also have some information on which systems/libs the server code is based on?
Thx

**Comment by david-wire** [comment]
End of Q1 2017 is the current plan indeed, but we do not have any more details to share at this stage. Please stay tuned. We will update this thread in due course.

**Comment by jspittka** [comment]
The server code now is open source: https://medium.com/@wireapp/wire-server-code-now-100-open-source-the-journey-continues-88e24164309c
