### ISSUE TITLE
The lack of file?

### ISSUE THREAD

**Issue by huangzhangliang** [wireapp/wire-audio-video-signaling#15]
wire-audio-video-signaling-master\mediaengine\webrtc  There is no file?

**Comment by mikeger** [comment]
Hey @huangzhangliang ! The WebRTC code is included as a git submodule:
![screen shot 2018-03-12 at 10 46 01](https://user-images.githubusercontent.com/715129/37276660-a7a74006-25e2-11e8-8120-50885f9dc203.png)

Please run 
`$ ./prepare.sh` 
in order to fetch it.
