### ISSUE TITLE
AVS Release 5.3（arm64 ndk build failed）

### ISSUE THREAD

**Issue by webrtcman** [wireapp/wire-audio-video-signaling#18]
make WEBRTC_VER=72.local dist_android 
armv7 is ok:
[armeabi-v7a] Compile++ thumb: avs <= flow_manager.cc
[armeabi-v7a] Compile++ thumb: avs <= media_manager.cc
[armeabi-v7a] Compile++ thumb: avs <= video_renderer.cc
[armeabi-v7a] Compile++ thumb: avs <= audio_effect.cc
[armeabi-v7a] SharedLibrary  : libavs.so
[armeabi-v7a] Install        : libavs.so => libs/armeabi-v7a/libavs.so

But arm64 is failed:
......

/home/ryan/wire-audio-video-signaling/build/toolchains/android-arm64/ndk/ndk-build -C android -I ../build/android-arm64
Android NDK: WARNING: APP_PLATFORM android-21 is higher than android:minSdkVersion 1 in ./AndroidManifest.xml. NDK binaries will *not* be comptible with devices older than android-21. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md for more information.    
Android NDK: WARNING:jni/Android.mk:avs: non-system libraries in linker flags: -lavscore -lre -lrew -lsodium -lwebrtc -lc++_static -lc++abi    
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES    
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the    
Android NDK:     current module    

make[1]: Entering directory `/home/ryan/wire-audio-video-signaling/android'
[arm64-v8a] Compile++      : avs <= flow_manager.cc
[arm64-v8a] Compile++      : avs <= media_manager.cc
[arm64-v8a] Compile++      : avs <= video_renderer.cc
[arm64-v8a] Compile++      : avs <= audio_effect.cc
[arm64-v8a] SharedLibrary  : libavs.so

/home/ryan/devtools/android-ndk-r16b/build/../sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++_static.a(locale.o): In function `float std::__ndk1::__do_strtod<float>(char const*, char**)':
/usr/local/google/buildbot/src/android/ndk-release-r16/external/libcxx/include/locale:807: undefined reference to `strtof_l'
/home/ryan/devtools/android-ndk-r16b/build/../sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++_static.a(locale.o): In function `double std::__ndk1::__do_strtod<double>(char const*, char**)':
/usr/local/google/buildbot/src/android/ndk-release-r16/external/libcxx/include/locale:813: undefined reference to `strtod_l'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [obj/local/arm64-v8a/libavs.so] Error 1
make[1]: Leaving directory `/home/ryan/wire-audio-video-signaling/android'
mk/dist.mk:149: recipe for target '/home/ryan/wire-audio-video-signaling/build/dist/android/avs.aar' failed
make: *** [/home/ryan/wire-audio-video-signaling/build/dist/android/avs.aar] Error 2

I had try NDK r16b 、r17、r18、r19、r20.  All are same error.
I don't know how to solve this problem. who can help me? thanks.

**Comment by Freeverc** [comment]
Same Problem.Did you solve it?
