### ISSUE TITLE
Homebrew is not able to install multirust on Mac 

### ISSUE THREAD

**Issue by lucifer662607004** [wireapp/wire-audio-video-signaling#19]
There is no such dependency on home-brew( or it has been removed):

> brew info multirust
> Error: No available formula with the name "multirust" 
> ==> Searching for a previously deleted formula (in the last month)...
> Warning: homebrew/core is shallow clone. To get complete history run:
>   git -C "$(brew --repo homebrew/core)" fetch --unshallow
> 
> Error: No previously deleted formula found.

When I tried to build multirust from source it failed on fetching one of its submodule:

> git clone --depth=1 https://github.com/brson/multirust && cd multirust
> ...
> git submodule update --init --recursive
> fatal: not a git repository (or any of the parent directories): .git
> newrock@ZhaodeMac-mini GitProject % cd multirust                           
> newrock@ZhaodeMac-mini multirust % git submodule update --init --recursive                                           
> error: Server does not allow request for unadvertised object aa5ffc99caf4864b2928bc5d5be37c483ab0eba0
> Fetched in submodule path 'src/rustup', but it did not contain aa5ffc99caf4864b2928bc5d5be37c483ab0eba0. Direct fetching of that commit failed.

And the README says it has migrated to rustup.rs

Any ideas to make it work? Thanks in advance.

**Comment by franziskuskiefer** [comment]
The documentation on this is unfortunately pretty outdated. You don't need multirust.
