### ISSUE TITLE
Git submodule is not fetching contrib/re...

### ISSUE THREAD

**Issue by lucifer662607004** [wireapp/wire-audio-video-signaling#20]
steven@stevens-MBP WireAVS % git submodule init
steven@stevens-MBP WireAVS % git submodule update
steven@stevens-MBP WireAVS % git submodule foreach git fetch
Entering 'contrib/cryptobox-c'
Entering 'contrib/generic-message-proto'
Entering 'contrib/googletest'
Entering 'contrib/rem'
Entering 'contrib/rew'
Entering 'contrib/sodium'

There is no contrib/re.
The contrib/re files are missing during final make command. 
But I can git clone 're' manually into contrib folder and everything works fine.
Please fix the submodule config.

**Comment by jspittka** [comment]
Thanks for reporting. Should be fixed with commit 979e3895d6b959c2b9ae122f9f15ad6f1cccee85.
