### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [wireapp/wire-audio-video-signaling#7]
I would like to point out that identifiers like "[`AVS_H__`](https://github.com/wireapp/avs/blob/fdd588aa9a6175211cd76d56b5a7ff798ad5ab31/include/avs.h#L18)" and "[`ZCLIENTCALL__ENGINE_H`](https://github.com/wireapp/avs/blob/fdd588aa9a6175211cd76d56b5a7ff798ad5ab31/include/avs_engine.h#L22)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by jspittka** [comment]
Thanks for taking the time to review our code and for pointing out this issue! I have created a ticket for our backlog.

**Comment by elfring** [comment]
Would it be safer to keep this issue open until it will be really fixed?
